import { expect, test, type Page, type APIRequestContext } from "@playwright/test";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import type { ApplicationView } from "../lib/service/types";
import type { ListingsView } from "../lib/jobs/types";
import { REFERENCE_COLUMNS } from "../lib/pipeline/types";

const ready = JSON.parse(readFileSync("output/live-acceptance/fictional-ready.json", "utf8"));
const ats = ready.atsOrigin as string;
const card = (page: Page, company: string) => page.locator("article.card", { hasText: company });
const listing = (page: Page, role: string) => page.locator("article.listing", { hasText: role });
const digest = (data: Buffer) => createHash("sha256").update(data).digest("hex");
const api = async (request: APIRequestContext, path: string) => (await request.get(`/api/imx${path}`)).json();
const submissions = async (request: APIRequestContext, job: string) => (await request.get(`${ats}/__test__/submissions?job_id=${job}`)).json();

async function start(page: Page, url: string) {
  await expect(page.getByLabel("First name")).toHaveValue("Avery");
  await page.getByLabel("Application link").fill(url);
  const response = page.waitForResponse((r) => r.url().endsWith("/api/imx/applications") && r.request().method() === "POST");
  await page.getByRole("button", { name: "Apply and submit" }).click();
  return response;
}

test("real J1 search, J2 decision, preferences and pipeline tracking", async ({ page, request }) => {
  await page.goto("/jobs");
  await expect(page.getByText("Test mode", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Search", exact: true }).click();
  await expect(page.locator("article.listing")).toHaveCount(2);
  await page.locator(".sources__summary").click();
  await expect(page.getByText("Fictional source asks you to sign in", { exact: true })).toBeVisible();
  await page.locator(".sources__summary").click();
  const data: ListingsView = await api(request, "/jobs");
  expect(data.listings.map((item) => item.locationTier)).toEqual(["ONSITE_HYBRID_TARGET", "REMOTE_ELIGIBLE"]);
  const austin = listing(page, "Paid Acquisition Lead");
  await austin.getByRole("button", { name: "Ask Jev", exact: true }).click();
  await expect(austin.getByRole("button", { name: "Ask Jev again", exact: true })).toBeEnabled();
  const before = await api(request, `/jobs/${data.listings[0].id}`);
  expect(before.decisionTask.state).toBe("DONE");
  expect(before.selection).not.toBeNull();
  await austin.getByRole("button", { name: "Ask Jev again", exact: true }).click();
  await expect(austin.getByRole("button", { name: "Ask Jev again", exact: true })).toBeEnabled();
  const cached = await api(request, `/jobs/${data.listings[0].id}`);
  expect(cached.decisionTask.state).toBe("DONE");
  expect(cached.selection.id).toBe(before.selection.id);
  const remote = listing(page, "Performance Marketing Manager");
  await remote.getByRole("button", { name: "Ask Jev", exact: true }).click();
  await expect(remote.getByText("Not established", { exact: true })).toBeVisible();
  await expect(remote).toContainText("Pay isn't stated");
  await austin.getByRole("button", { name: "Track in pipeline" }).click();
  await expect(austin.getByRole("link", { name: "In your pipeline" })).toBeVisible();
  await page.getByRole("button", { name: "Edit preferences" }).click();
  const role = page.getByRole("dialog").getByLabel("Role focus");
  await role.fill((await role.inputValue()) + " Prioritize hands-on paid search ownership.");
  await page.getByRole("dialog").getByRole("button", { name: "Save preferences", exact: true }).click();
  await expect(austin).toContainText("Your preferences or this listing changed");
  await page.reload();
  expect((await api(request, "/selection/preferences")).roleFocus).toContain("Prioritize hands-on paid search ownership");
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: "output/astra-live-jobs-desktop.png" });
  await page.goto("/pipeline");
  await expect(card(page, "Fictional Austin Marketing")).toContainText("Paid Acquisition Lead");
  await expect(card(page, "Fictional Austin Marketing").locator(".mark--receipt")).toHaveCount(0);
  expect((await submissions(request, "standard")).accepted_count).toBe(0);
});

test("frontend to real runner submits once, links receipt and protects duplicate", async ({ page, request }, info) => {
  await page.goto("/pipeline");
  await card(page, "Fictional Austin Marketing").getByRole("button", { name: /^Apply/ }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Continue to the desk" }).click();
  await expect(page).toHaveURL(ready.frontendOrigin + "/");
  const response = await start(page, `${ats}/jobs/standard`);
  expect(response.status()).toBe(201);
  const started: ApplicationView = await response.json();
  await expect(page.locator("#case-title")).toHaveText("Submitted and confirmed");
  const view: ApplicationView = await api(request, `/applications/${started.id}`);
  const receipt = await submissions(request, "standard");
  expect(receipt.accepted_count).toBe(1);
  expect(view.job.title).toBe(ready.fixtureJobs.standard.title);
  expect(receipt.submissions[0].job_title).toBe("Paid Acquisition Lead");
  expect(receipt.submissions[0].company).toBe("Fictional Austin Marketing");
  expect(view.receipt?.confirmationReference).toBe(receipt.submissions[0].confirmation_reference);
  expect(view.receipt?.confirmationAuthority).toBe("site");
  expect(receipt.submissions[0].files.resume.sha256).toBe(digest(readFileSync(`${ready.home}/profile/default/resume.pdf`)));
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: "output/astra-live-receipt-desktop.png" });
  await info.attach("standard-receipt", { body: JSON.stringify({ applicationId: started.id, receipt: view.receipt, acceptedCount: receipt.accepted_count }), contentType: "application/json" });
  await page.getByRole("button", { name: "Start another application" }).click();
  const duplicate = await start(page, `${ats}/jobs/standard`);
  expect(duplicate.status()).toBe(200);
  expect((await duplicate.json()).id).toBe(started.id);
  await expect(page.locator("#case-title")).toHaveText("Submitted and confirmed");
  expect((await submissions(request, "standard")).accepted_count).toBe(1);
  await page.goto("/pipeline");
  await expect(card(page, "Fictional Austin Marketing").locator(".mark--receipt")).toContainText("Receipt confirmed");
});

test("missing answers survive reload and selected resume stays pinned", async ({ page, request }) => {
  const earlierCount = (await submissions(request, "standard")).accepted_count;
  await page.goto("/");
  const resume = Buffer.from("%PDF-1.4\n% second fictional resume for Avery Quill\n%%EOF\n");
  await page.locator("#resume-file").setInputFiles({ name: "Avery Quill second.pdf", mimeType: "application/pdf", buffer: resume });
  await expect(page.getByRole("radio", { name: /Avery Quill second/ })).toBeChecked();
  const response = await start(page, `${ats}/jobs/missing-required/apply`);
  expect(response.status()).toBe(201);
  const started: ApplicationView = await response.json();
  await expect(page.locator("#case-title")).toContainText("needed from you");
  expect((await submissions(request, "missing-required")).accepted_count).toBe(0);
  const view: ApplicationView = await api(request, `/applications/${started.id}`);
  if (view.needs?.kind !== "questions") throw new Error("Expected persisted factual questions");
  for (const question of view.needs.questions) {
    const control = page.locator(`[id="${question.id}"]`);
    if (question.control === "single_select") {
      const options = question.options ?? [];
      expect(options.map((o) => o.label)).not.toContain("3 months or more (no longer offered)");
      const option = options.find((o) => o.label === "2 weeks") ?? options.find((o) => o.label === "No") ?? options[0];
      if (options.length > 6) await control.selectOption(option.value);
      else await control.getByRole("radio", { name: option.label, exact: true }).check();
    } else await control.fill("150000");
  }
  await page.getByRole("button", { name: "Save for later" }).click();
  await expect(page.locator(".questions__saved")).toContainText("Saved at");
  await page.reload();
  await expect(page.locator("#case-title")).toContainText("needed from you");
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: "output/astra-live-questions-desktop.png" });
  await page.getByRole("button", { name: "Save answers and continue" }).click();
  await expect(page.locator("#case-title")).toHaveText("Submitted and confirmed");
  const receipt = await submissions(request, "missing-required");
  expect(receipt.accepted_count).toBe(1);
  expect(receipt.submissions[0].fields.salary_expectation).toBe("150000");
  expect(receipt.submissions[0].files.resume.sha256).toBe(digest(resume));
  expect((await submissions(request, "standard")).accepted_count).toBe(earlierCount);
});

test("uncertain submission stays locked through report and settles only on site proof", async ({ page, request }) => {
  await page.goto("/");
  const response = await start(page, `${ats}/jobs/uncertain`);
  const started: ApplicationView = await response.json();
  await expect(page.locator("#case-title")).toHaveText("Submission not confirmed");
  expect((await submissions(request, "uncertain")).accepted_count).toBe(1);
  await expect(page.getByRole("button", { name: /retry|try again/i })).toHaveCount(0);
  await page.getByRole("button", { name: "The employer has no record of it" }).click();
  const statement = page.getByRole("checkbox", { name: /I checked with the employer/ });
  await expect(statement).not.toBeChecked();
  await statement.check();
  await page.getByRole("button", { name: "Record as not received" }).click();
  await expect(page.locator(".check-result")).toBeVisible();
  expect((await api(request, `/applications/${started.id}`)).state).toBe("SUBMISSION_UNKNOWN");
  await page.getByRole("button", { name: "Check the site again" }).click();
  await expect(page.getByRole("button", { name: "Check the site again" })).toBeEnabled();
  await expect(page.locator("#case-title")).toHaveText("Submission not confirmed");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: "output/astra-live-uncertain-mobile.png" });
  const receipt = await submissions(request, "uncertain");
  await request.post(`${ats}/__test__/submissions/${receipt.submissions[0].submission_id}/reveal`);
  await page.getByRole("button", { name: "Check the site again" }).click();
  await expect(page.locator("#case-title")).toHaveText("Submitted and confirmed");
  const settled: ApplicationView = await api(request, `/applications/${started.id}`);
  expect(settled.receipt?.confirmationMethod).toBe("SITE_CONFIRMATION");
  expect(settled.receipt?.confirmationAuthority).toBe("site");
  expect((await submissions(request, "uncertain")).accepted_count).toBe(1);
});

test("real pipeline edits, lane history and repeated import survive reload", async ({ page, request }) => {
  await page.goto("/pipeline");
  await card(page, "Fictional Austin Marketing").getByRole("button", { name: "Open Fictional Austin Marketing" }).click();
  const edit = page.getByRole("dialog");
  await edit.getByLabel("Next action", { exact: true }).fill("Prepare two paid-search experiment examples.");
  await edit.getByLabel("Location / commute", { exact: true }).fill("Austin office, 25-minute commute each way");
  await edit.getByRole("button", { name: "Save changes" }).click();
  await expect(edit).toBeHidden();
  await card(page, "Fictional Austin Marketing").getByLabel("Move Fictional Austin Marketing to lane").selectOption("follow-up");
  await card(page, "Fictional Austin Marketing").getByRole("button", { name: "Move", exact: true }).click();
  await page.reload();
  await expect(card(page, "Fictional Austin Marketing")).toContainText("Prepare two paid-search experiment examples");
  await page.getByRole("button", { name: "Import", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Tracker name").fill("fictional-paid-media-tracker");
  const file = (next: string) => {
    const values: Record<string, string> = { company: "Fictional Orchard", role: "Paid Media Manager", nextAction: next, compensationLow: "125000" };
    return { name: "fictional.csv", mimeType: "text/csv", buffer: Buffer.from(REFERENCE_COLUMNS.map((c) => c.header).join(",") + "\n" + REFERENCE_COLUMNS.map((c) => values[c.field] ?? "").join(",") + "\n") };
  };
  await dialog.locator("#import-file").setInputFiles(file("Review the role"));
  await expect(dialog.locator(".import__counts")).toContainText("1 new");
  await dialog.getByRole("button", { name: "Import 1 row" }).click();
  await expect(dialog.locator(".import__receipt")).toContainText("1 new");
  await dialog.locator("#import-file").setInputFiles(file("Review the updated role"));
  await expect(dialog.locator(".import__counts")).toContainText("0 new · 1 updated");
  await dialog.getByRole("button", { name: "Import 1 row" }).click();
  await expect(dialog.locator(".import__receipt")).toContainText("1 updated");
  await dialog.getByRole("button", { name: /^Close/ }).click();
  await page.reload();
  await expect(card(page, "Fictional Orchard")).toHaveCount(1);
  await expect(card(page, "Fictional Orchard")).toContainText("Review the updated role");
  const board = await api(request, "/pipeline");
  const austin = board.entries.find((item: { fields: { company: string } }) => item.fields.company === "Fictional Austin Marketing");
  expect(austin.lane).toBe("follow-up");
  const orchard = board.entries.find((item: { fields: { company: string } }) => item.fields.company === "Fictional Orchard");
  expect(orchard.provenance.importedValues["Next action"]).toBe("Review the role");
  expect(orchard.provenance.latestImportedValues["Next action"]).toBe("Review the updated role");
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: "output/astra-live-pipeline-desktop.png" });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: "output/astra-live-pipeline-mobile.png" });
});
