"""Interviewmaxxing canonical contracts, service interfaces and local store.

Import contracts from here (``from interviewmaxxing_core import ApplicationForm``) or
from their modules. Downstream packages must not redeclare any of these types.
"""

from ._base import CONTRACT_VERSION, Contract, new_id, utc_now
from .applications import (
    PRE_SUBMISSION_STATES,
    SUBMISSION_BLOCKING_STATES,
    TERMINAL_STATES,
    TRANSITIONS,
    Application,
    ApplicationEvent,
    ApplicationRequest,
    ApplicationState,
    Claim,
    Receipt,
    RequestDisposition,
    SubmissionAttempt,
    can_transition,
)
from .artifacts import ArtifactRef, EvidenceKind, EvidenceRef, sha256_file
from .candidate import (
    CandidateFact,
    CandidateIdentity,
    CandidateProfile,
    Education,
    Experience,
    PostalAddress,
    ResumeArtifact,
    SavedAnswer,
)
from .config import LocalPaths
from .errors import (
    ClaimLost,
    ClaimUnavailable,
    IdentityConflict,
    InvalidTransition,
    NotFound,
    StoreError,
    SubmissionBlocked,
)
from .execution import (
    USER_ACTION_PAGES,
    FieldFillResult,
    FieldFillStatus,
    FillResult,
    NavigationResult,
    NotSubmittedNext,
    PageInspection,
    PageKind,
    ReconciliationMethod,
    SubmissionObservation,
    SubmissionOutcome,
    SubmissionReconciliation,
    SubmitActionResult,
)
from .forms import (
    EXPLICIT_ANSWER_REQUIRED,
    PROTECTED_ATTRIBUTE_TYPES,
    ApplicationField,
    ApplicationForm,
    ControlType,
    FieldOption,
    SemanticType,
)
from .interfaces import (
    ApplicationBrowser,
    ApplicationRunner,
    ApplyOutcome,
    ATSAdapter,
    BrowserOptions,
    BrowserSessionFactory,
    CandidateLoader,
    CandidateNotFound,
    CandidateProfileInvalid,
    PacketContext,
    PacketResolver,
    UserInteraction,
)
from .jobs import IdentityEvidenceKind, JobIdentityObservation, JobRecord
from .packets import (
    AnswerSource,
    AnswerValue,
    ApplicationPacket,
    BooleanValue,
    ChoiceValue,
    FileValue,
    MissingInput,
    MissingReason,
    MultiChoiceValue,
    PacketAnswer,
    Provenance,
    TextValue,
    UserInput,
    answer_problems,
)
from .store import ApplicationStore, BindResult, RequestResult
from .urls import InvalidApplicationUrl, normalize_application_url

__all__ = [
    "CONTRACT_VERSION",
    "EXPLICIT_ANSWER_REQUIRED",
    "PRE_SUBMISSION_STATES",
    "PROTECTED_ATTRIBUTE_TYPES",
    "SUBMISSION_BLOCKING_STATES",
    "TERMINAL_STATES",
    "TRANSITIONS",
    "USER_ACTION_PAGES",
    "ATSAdapter",
    "AnswerSource",
    "AnswerValue",
    "Application",
    "ApplicationBrowser",
    "ApplicationEvent",
    "ApplicationField",
    "ApplicationForm",
    "ApplicationPacket",
    "ApplicationRequest",
    "ApplicationRunner",
    "ApplicationState",
    "ApplicationStore",
    "ApplyOutcome",
    "ArtifactRef",
    "BindResult",
    "BooleanValue",
    "BrowserOptions",
    "BrowserSessionFactory",
    "CandidateFact",
    "CandidateIdentity",
    "CandidateLoader",
    "CandidateNotFound",
    "CandidateProfile",
    "CandidateProfileInvalid",
    "ChoiceValue",
    "Claim",
    "ClaimLost",
    "ClaimUnavailable",
    "Contract",
    "ControlType",
    "Education",
    "EvidenceKind",
    "EvidenceRef",
    "Experience",
    "FieldFillResult",
    "FieldFillStatus",
    "FieldOption",
    "FileValue",
    "FillResult",
    "IdentityConflict",
    "IdentityEvidenceKind",
    "InvalidApplicationUrl",
    "InvalidTransition",
    "JobIdentityObservation",
    "JobRecord",
    "LocalPaths",
    "MissingInput",
    "MissingReason",
    "MultiChoiceValue",
    "NavigationResult",
    "NotFound",
    "NotSubmittedNext",
    "PacketAnswer",
    "PacketContext",
    "PacketResolver",
    "PageInspection",
    "PageKind",
    "PostalAddress",
    "Provenance",
    "Receipt",
    "ReconciliationMethod",
    "RequestDisposition",
    "RequestResult",
    "ResumeArtifact",
    "SavedAnswer",
    "SemanticType",
    "StoreError",
    "SubmissionAttempt",
    "SubmissionBlocked",
    "SubmissionObservation",
    "SubmissionOutcome",
    "SubmissionReconciliation",
    "SubmitActionResult",
    "TextValue",
    "UserInput",
    "UserInteraction",
    "answer_problems",
    "can_transition",
    "new_id",
    "normalize_application_url",
    "sha256_file",
    "utc_now",
]
